### ISSUE TITLE
Working example for graph with real number weights

### ISSUE THREAD

**Issue by MdAsifKhan** [dongguosheng/deepwalk#1]
Hi,
How can I use it for graph with real number weights?
I get the segmentation fault when I run it on one of my graph in edgelist format.
Could you please provide a working example of it.

Thanks,
Asif

**Comment by dongguosheng** [comment]
Hi Asif,
real number weight is supported now and the updated README provides a working example.

**Comment by MdAsifKhan** [comment]
Thanks Dong Guosheng,
           Great work.!, it works now. However, embedding generated from deepwalk have quite big values mostly 3 or 4 digit integer. Is it because of weight or is there any reason.

**Comment by dongguosheng** [comment]
the original deepwalk algorithm includes 2 steps: 1. generate walks file as word2vec training input; 2. word2vec training. Which word2vec package did you use?

**Comment by MdAsifKhan** [comment]
gensim, seems some issue with word2vec training. I will debug my code.

Thanks

**Comment by dongguosheng** [comment]
maybe you can try to check your walks file, does the walks make sense? I tested on my data and result seems ok.

**Comment by MdAsifKhan** [comment]
something was wrong with gensim, I updated it now it works fine. 
Thanks.!
