### ISSUE TITLE
Walks for Directed Graph

### ISSUE THREAD

**Issue by MdAsifKhan** [dongguosheng/deepwalk#2]
Hi Dong Guosheng,
        Great work, works good for weighted undirected graph. Was wondering to experiment it on directed graph. Is there any specific configuration to use it for weighted directed graph.

**Comment by dongguosheng** [comment]
Right now directed graph is not supported, but it shouldn't be very hard if update the code.
is there any real application scenarios that the graph has to be directed?

**Comment by MdAsifKhan** [comment]
Yes lot's of such graph are there in bioinformatics where challenge is to identify shortest path or to do modularity analysis etc. As in original deepwalk I think it can be used for directed graph. I think modification should be only with random walk to make it work. 

You have any suggestion how to do it with your implementation?

Thanks

**Comment by dongguosheng** [comment]
Directed graph is supported now, have a try. Feel free to contact me if there's any problem.

**Comment by MdAsifKhan** [comment]
thanks, great work.!
