### ISSUE TITLE
Some issues with dense graph

### ISSUE THREAD

**Issue by MdAsifKhan** [dongguosheng/deepwalk#3]
Hi,
 It works well, but for few dense graph I get following error while loading edgelist:
walk: deepwalk.h:103: bool deepwalk::Graph<T>::LoadEdgeList(const char*, int) [with T = unsigned int]: Assertion `id_right < data.size()' failed.

**Comment by dongguosheng** [comment]
Is some id equal or larger than the total number of vertex, param `num_vertex`? What is the output after running `scripts/validate_graph.py`?

**Comment by MdAsifKhan** [comment]
yes it is so. There are 10K nodes in total and few of them have id's greater then 10K.
How to fix it for such graph??

**Comment by dongguosheng** [comment]
What is the output after running `scripts/validate_graph.py`?
Now the vertex ids in graph file have to be continuous, like [0, 1, 2, 3, 4, 5], number of node is 6 and start index is 0 or [1, 2, 3, 4, 5], number of node is 5, start index is 1.

**Comment by MdAsifKhan** [comment]
(invalid) lost vid, total 10405 vertex, n_max=10474
graph edgelist is in following format:
 Node1 Node2  Weight
node1 is continuous

**Comment by dongguosheng** [comment]
If start index is 0, there are `10474-10405+1` node ids never occured in the graph edgelist, that is not supported now.
I just updated the code, try again please. The second arg is max node index now.

**Comment by MdAsifKhan** [comment]
Now it gives following error:
walk: deepwalk.h:105: bool deepwalk::Graph<T>::LoadEdgeList(const char*, int, bool) [with T = unsigned int]: Assertion `id_left < data.size()' failed.

**Comment by dongguosheng** [comment]
Could you please show me the output of running `scripts/validate_graph.py` and the arglist of walk?
Seems like one of you node index is larger than the max node index, that should't happen.

**Comment by MdAsifKhan** [comment]
I get this with validate_graph.py
(valid) start index: 0, max vertex idx: 10474, total 10405 vertex.
vertex ids are not continuous, lost 69 id.

**Comment by MdAsifKhan** [comment]
Works now one of the argument was missing.
