### ISSUE TITLE
Random number generator for float values less than 1

### ISSUE THREAD

**Issue by tejasshah93** [dongguosheng/deepwalk#4]
Hi,

Considering the case wherein the edge weights are floating point numbers between 0 and 1, the lower bound for generating random number (specified on [L194](https://github.com/dongguosheng/deepwalk/blob/master/deepwalk.h#L194)) need to be set to 0 in order to contain the distribution upto the net cumulative sum.
Also, if I'm not wrong, even if the edge weights are not scaled between 0 and 1, the lower bound of 0 would still work. Can the range be modified in order to accommodate all the possible cases by updating the lower bound?

**Comment by dongguosheng** [comment]
You are right. The lower bound of the uniform rng should be 0, suppose that all edge weights are positive floating point numbers. Thanks for catching this bug and I fixed it in https://github.com/dongguosheng/deepwalk/commit/47b6e4d6334f683d4c2df187f0b97a23867a172a

**Comment by tejasshah93** [comment]
Thanks for the prompt response and the fix. Much appreciated :+1: 
Closing this issue.
